#!/bin/bash
(Rscript simulations_get_osca.r ../simulations/simulated_data)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_2)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_4)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_5)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_6)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_7)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_8)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_9)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_10)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_11)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_12)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_13)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_14)&
(Rscript simulations_get_osca.r ../simulations/simulated_data_15)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_2)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_4)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_5)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_6)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_7)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_8)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_9)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_10)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_11)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_12)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_13)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_14)&
(Rscript simulations_get_osca.r ../simulations_no_sparse/simulated_data_15)&
