args = commandArgs(trailingOnly=TRUE)
simulation_root<-args[1]
simulations<-unique(dirname(list.files(path=simulation_root,pattern=".*dat",full.names=T,recursive=T)))
library(stats)
library(data.table)
lapply(simulations,function(simulation_dir){
   print(simulation_dir) 
   m_file=list.files(path=simulation_dir,pattern=".*_M.dat",full.names=T,recursive=T)
   print(m_file)
   print("reading methylation matrix")
   M <- as.matrix(fread(m_file))
   b_file=list.files(path=simulation_dir,pattern=".*_B.dat",full.names=T,recursive=T)
   print(b_file) 
   B <- as.matrix(fread(b_file))
   y_file=list.files(path=simulation_dir,pattern=".*_y.dat",full.names=T,recursive=T)
   print(y_file)
   Bg_file=gsub("B","Bg",b_file)
   print(Bg_file)
   X_file=gsub("M","X",m_file)
   print(X_file)
   
   markers<-dim(M)[2]
   print(markers)
   samples<-dim(M)[1]
   print(samples)
   print("generating genotype")
   X<- matrix(rbinom(markers*samples,2,0.5),nrow=samples,ncol=markers)
   X[,B!=0]<-apply(M[,B!=0],MARGIN = 2,function(x){
  	cofcor<-runif(1,20,25)
  	tmp<-rbinom(samples,2,1/(1+exp(10-cofcor*x)))
  	if(sd(tmp)==0)
         tmp<-rbinom(samples,2,0.5)
        tmp
   })
   print("simulating effects")
   B[B!=0]<-rnorm(100,0,sqrt(0.5/100))
   Bg<-rep(0,markers)
   Bg[B!=0]<-rnorm(100,0,sqrt(0.2/100))
   
   Bg[sample(setdiff(1:markers,which(B!=0)),900)]<-rnorm(900,0,sqrt(0.1/900))
   print("simulating phenotype")
   y=scale(M)%*%as.matrix(B)+scale(X)%*%Bg+rnorm(samples,sd=sqrt(0.2))
   print(head(y))
   print("saving simulations phenotype")
   write.table(y,file=y_file,col.names=F,sep="\t")
    print("saving simulations genotype")
   write.table(X,file=X_file,col.names=F,sep="\t")
    print("saving simulations m. effects")
   write.table(B,file=b_file,col.names=F,sep="\t")
    print("saving simulations genetic effects")
   write.table(Bg,file=Bg_file,col.names=F,sep="\t")
   print("success in simulating genotype")
}
)
